### ISSUE TITLE
Does not work for `time.time_ns()`

### ISSUE THREAD

**Issue by kornsn** [ktosiek/pytest-freezegun#21] opened 2019-12-14 20:48 UTC
How to reproduce:
```python
async def test_freezer(freezer):
    print(time.time())
    print(time.time_ns())
    await asyncio.sleep(1)
    print(time.time())
    print(time.time_ns())
```
Result:
```
1576356147.404577
1576356147477996000
1576356147.404577
1576356148477304000
```
As we can see it freezes time for `time.time()`, but does not work for `time.time_ns()`.

**Comment by arusahni** [comment] 2020-01-14 18:04
Looks like this was fixed upstream? https://github.com/spulec/freezegun/pull/313

**Comment by ktosiek** [comment] 2020-01-14 21:14
Thank you for the heads up! I'm closing this as a duplicate of https://github.com/spulec/freezegun/issues/312, which got fixed upstream.

**Closed as completed by ktosiek** 2020-01-14 21:14 UTC
